
FROM node:16.17.0-alpine


WORKDIR /ProjectGrassFed/frontend


COPY package*.json ./

RUN apt-get update && \
    apt-get install -y npm

RUN npm install react react-dom


COPY . .


EXPOSE 3000


CMD ["npm", "start"]