# Use the official Python 3.9 image as the base image
FROM python:3.9-alpine as django_builder

# Set the working directory to /app/backend
WORKDIR /ProjectGrassFed/backend

# Copy the requirements.txt file to the container
COPY requirements.txt ./

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code to the container
COPY . .

# Expose port 8000 for the backend
EXPOSE 8000

# Start the development server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]